# ==========================================
#          AttributeCore 全局配置
# ==========================================

# 消息前缀
prefix: "&8[&bAttributeCore&8] &f"

# 战斗设置
combat:
  # 护甲公式中的 K 值。 K / (Armor + K)
  # 值越大，护甲越不容易达到高减伤。建议范围 300-500
  armor_k_value: 400.0


# 护盾系统设置
shield:
  # 护盾自动恢复开关
  auto_regen: true
  # 每秒恢复最大护盾的百分比 (0.05 = 5%)
  regen_speed: 0.05

# 元素系统设置
elements:
  # 附着持续时间 (tick)
  aura_duration: 100
  # 反应内置冷却 (ms)
  reaction_icd: 500

# 更新设置
update:
  # 属性刷新频率 (单位: tick, 20tick = 1s)
  # 越低实时性越好，但消耗性能越多
  refresh_interval: 20

# 调试模式 (开启后控制台会输出详细的计算过程)
debug: false